# Generated by Django 3.1 on 2020-08-12 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20200811_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(blank=True, choices=[('Gold', 'Brand New'), ('Silver', 'Used with love'), ('Bronze', 'Used with love for a longtime')], max_length=64, null=True),
        ),
    ]
