# Generated by Django 3.1 on 2020-08-12 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auto_20200812_0731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Gold', 'Brand New'), ('Silver', 'Used with love'), ('Bronze', 'Used with love for a longtime')], default='None', max_length=64, null=True),
        ),
    ]
