# Generated by Django 3.1 on 2020-08-13 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_auto_20200813_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='active',
            field=models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1),
        ),
    ]
