# Generated by Django 3.1 on 2020-08-13 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_auto_20200813_0751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='date',
        ),
    ]
