# Generated by Django 3.1 on 2020-08-20 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0025_auto_20200820_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='listing',
            name='initial_price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.bid'),
        ),
    ]
