# Generated by Django 3.1 on 2020-08-20 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0029_auto_20200820_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bet', to='auctions.listing'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='initial_price',
            field=models.IntegerField(),
        ),
    ]
