# Generated by Django 3.1 on 2020-08-20 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0034_auto_20200820_1126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='watchlist',
        ),
        migrations.AlterField(
            model_name='bid',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='bid',
            name='price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.listing'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='listing',
            name='date',
            field=models.DateField(),
        ),
        migrations.DeleteModel(
            name='Watch',
        ),
    ]
