# Generated by Django 3.1 on 2020-08-21 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0039_auto_20200821_0715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='created_by',
        ),
    ]
