# Generated by Django 3.1 on 2020-08-24 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0041_listing_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='created_by',
        ),
    ]
