# Generated by Django 3.1 on 2020-08-24 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0053_auto_20200824_0840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='watchlist',
        ),
    ]
