# Generated by Django 3.1 on 2020-08-24 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0054_remove_listing_watchlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='watchlist',
        ),
    ]
