# Generated by Django 3.1 on 2020-08-24 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0057_listing_watchlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='watchlist',
        ),
    ]
