# Generated by Django 3.1 on 2020-08-24 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0058_remove_listing_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='listing_list',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auctions.listing'),
        ),
    ]
