# Generated by Django 3.1 on 2020-08-24 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0059_watchlist_listing_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='listing_list',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='auctions.listing'),
        ),
    ]
