# Generated by Django 3.1 on 2020-08-24 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0060_auto_20200824_1013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='status',
        ),
    ]
