# Generated by Django 3.1 on 2020-08-24 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0061_remove_watchlist_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='listing_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.listing'),
        ),
    ]
