# Generated by Django 3.1 on 2020-08-24 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0064_auto_20200824_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='listing_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.listing'),
        ),
    ]
