# Generated by Django 3.1 on 2020-08-24 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0071_auto_20200824_1441'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='user',
            new_name='name',
        ),
    ]
