# Generated by Django 3.1 on 2020-08-24 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0073_auto_20200824_1446'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='name',
            new_name='owner',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='watchlist',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='date',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='status',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.listing'),
        ),
    ]
