# Generated by Django 3.1 on 2020-08-25 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0074_auto_20200824_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
