# Generated by Django 3.1 on 2020-08-25 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0076_auto_20200825_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='product',
        ),
    ]
