# Generated by Django 3.1 on 2020-08-25 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0080_auto_20200825_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='listing_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
