# Generated by Django 3.1 on 2020-08-28 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0082_listing_winner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClientAccount',
        ),
    ]
