# Generated by Django 3.1 on 2020-08-28 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0085_auto_20200828_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='winner',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='user',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
