# Generated by Django 3.1 on 2020-08-31 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0086_auto_20200828_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.AddField(
            model_name='comment',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
