# Generated by Django 3.1 on 2020-08-31 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0092_auto_20200831_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='comment',
            field=models.ManyToManyField(blank=True, to='auctions.Comment'),
        ),
    ]
