# Generated by Django 3.1 on 2020-08-31 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0094_comment_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='product_title',
            field=models.CharField(default='ben', max_length=100),
            preserve_default=False,
        ),
    ]
