# Generated by Django 3.1 on 2020-09-01 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0095_watchlist_product_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Gold', 'Expert'), ('Silver', 'Senior'), ('Bronze', 'Entry level')], default='None', max_length=64, null=True),
        ),
    ]
