# Generated by Django 3.1 on 2020-09-02 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0096_auto_20200901_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Gold', 'Rockstar'), ('Silver', 'Chef'), ('Bronze', 'Junior')], default='None', max_length=64, null=True),
        ),
    ]
