# Generated by Django 3.1 on 2020-09-02 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0097_auto_20200902_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(blank=True, choices=[('NADA', 'None'), ('GOLD', 'Rockstar'), ('SILVER', 'Chef'), ('BRONZE', 'Junior')], default=2, max_length=64, null=True),
        ),
    ]
