# Generated by Django 3.1 on 2020-09-04 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0099_auto_20200902_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(blank=True, choices=[(3, 'Rockstar'), (4, 'Chef'), (5, 'Junior')], max_length=64, null=True),
        ),
    ]
