# Generated by Django 3.1 on 2020-09-04 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0103_auto_20200904_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.IntegerField(blank=True, choices=[(1, 'GOLD'), (2, 'SILVER'), (3, 'BRONZE')], default=None, null=True),
        ),
    ]
