# Generated by Django 4.2.7 on 2023-12-06 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0104_auto_20200904_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.IntegerField(blank=True, choices=[(1, 'HEALTH'), (2, 'MOTOR'), (3, 'FOOD')], default=None, null=True),
        ),
    ]
